// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "David":return img`
..............................
...........ddddddd............
...........d11d11d............
...........d1fd1fd............
...........d11d11d............
...........ddddddd............
..dddd.......ddd..............
..dddd.......ddd..............
..dddd...dddddddddddd.........
...dd....dddddddddddd...ffffff
...dd....dddeddddeddd...ffffff
...dddddddddddddddddddddffdfd.
...dddddddddddddddddddddff....
.........dddddddddddd.........
.........dddddddddddd.........
.........dddddddddddd.........
.........dddddddddddd.........
.........eeeeeeeeeeee.........
.........eeeeeeeeeeee.........
.........eeeeeeeeeeee.........
.........eeee....eeee.........
.........eeee....eeee.........
.........eeee....eeee.........
..........dd......dd..........
..........dd......dd..........
..........dd......dd..........
..........dd......dd..........
..........dd......dd..........
..........ee......ee..........
..........eee.....eee.........
`;
            case "image2":
            case "Hussein":return img`
. . . . e e e e . . . . . 
. . . e e e e e e . . . . 
. . e e f e e f e e . . . 
. e e e e e e e e e e . . 
e e e e 1 e e e 1 e e e e 
e e f f f f f f f f e e e 
e e e e e e e e e e e e e 
. . d d d d d d d . . . . 
e e e e d d d d e e e e . 
e e e e . . . . e e e e . 
`;
            case "image3":
            case "Larry":return img`
...55555.......
...51155.......
5555f155.......
55551155.......
55555555.......
....555........
....555........
...ddddddd17...
...ddddddd177..
555dbbbbdd5557.
555ddddddd55577
...dbbbbdd17777
...ddddddd17777
...dbbbbdd17777
...ddddddd17777
...dbbbbdd1777.
...ddddddd177..
...ddddddd17...
...55...55.....
...55...55.....
...55...55.....
...55...55.....
...55...55.....
..777...777....
..777...777....
`;
            case "image4":
            case "Bullet":return img`
2 2 2 
2 1 2 
2 2 2 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Davy":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
